name: Setup Wild KSU
description: Download and configure Wild KSU with version tracking
inputs:
  ksu_commit:
    description: 'KSU commit to use (leave empty for canary)'
    required: false
    default: ''
  kernel_root:
    description: 'Path to kernel root directory'
    required: true

runs:
  using: composite
  steps:
    - name: Download Wild KSU
      shell: bash
      working-directory: ${{ inputs.kernel_root }}
      run: |
        echo "========================================"
        echo "        Setting up Wild KSU             "
        echo "========================================"
        if [[ -n "${{ inputs.ksu_commit }}" ]]; then
          echo "Using commit: ${{ inputs.ksu_commit }}"
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s "${{ inputs.ksu_commit }}"
        else
          echo "dev"
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s dev
        fi
    
    - name: Extract KSU Version Info
      id: ksu-version
      shell: bash
      working-directory: ${{ inputs.kernel_root }}/KernelSU-Next
      run: |
        KSU_GIT_VERSION=$(git rev-list --count HEAD 2>/dev/null)
        KSU_GIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null)
        KSU_COMMIT=$(git rev-parse --short HEAD 2>/dev/null)
        KSU_VERSION=$((30000 + KSU_GIT_VERSION))
        
        echo "KSU_GIT_TAG=$KSU_GIT_TAG" >> $GITHUB_ENV
        echo "KSU_VERSION=$KSU_VERSION" >> $GITHUB_ENV
        echo "KSU_COMMIT=$KSU_COMMIT" >> $GITHUB_ENV
        
        echo "✓ Wild KSU Setup Complete"
        echo "  Tag     : $KSU_GIT_TAG"
        echo "  Version : $KSU_VERSION"
        echo "  Commit  : $KSU_COMMIT"
        echo "========================================"
